[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
	'@openzeppelin/=node_modules/@openzeppelin/',
	'@ensdomains/=node_modules/@ensdomains/'
]

optimizer = true
optimizer_runs = 420